site_name: My Static Site
site_description: A custom static site built with MkDocs
theme:
  name: material
extra_css:
  - css/styles.css
extra_javascript:
  - js/script.js
markdown_extensions:
  - toc
  - footnotes
plugins:
  - minify